import { PageProps } from "~/types";
import "./globals.css";
import { Rubik } from "next/font/google";
import { dir } from "i18next";
import { locales } from "~/i18n/settings";
import LocaleSwitcher from "~/i18n/LocaleSwitcher";

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: PageProps<
  {},
  {
    children: React.ReactNode;
  }
>) {
  return (
    <html
      lang={locale}
      dir={dir(locale)}
      className={`${rubik.className} bg-slate-950 text-slate-400`}
    >
      <body className="p-4">
        <main>{children}</main>
        <LocaleSwitcher locale={locale} />
      </body>
    </html>
  );
}
