name: Build web

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0
          cache: pnpm

      - name: Setup PNPM
        run: corepack enable && pnpm -v

      - uses: jongwooo/next-cache@v1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web
        run: pnpm run build
